import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainLayoutClient from "./(mainpages)/MainLayoutClient";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Elysium",
  description: "Generated by Saleh Sheikh",
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="icon" href="/assets/icons/logo.svg" type="image/svg+xml" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full overflow-hidden`}>
       <MainLayoutClient>{children}</MainLayoutClient>
      </body>
    </html>
  );
}
