import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Elysium",
  description: "Generated by Saleh sheikh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
      <link rel="icon" href="/assets/icons/logo.svg" type="svg"  />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-full">
          {/* Sidebar on the left */}
          <Sidebar />

          {/* Right content (Navbar + Main Content) */}
          <div className="flex-1 flex flex-col">
            <Navbar />
            <main className="flex-1 overflow-auto">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
